### ISSUE TITLE
ILAConfig example_dut error in place and route step: X_CONVERT Netlist Converter 

### ISSUE THREAD

**Issue by alfredogardel** [colognechip/gatemate_ila#1]
Dear Dave, 
I've tried to implement and use the ILAcop for the example_dut blink but exits with an error. 

**X_CONVERT Netlist Converter

Library Mode used: CCAG_GateMate
#### Error: Exception Handler called. ExitCode: 112
Exception Class: EConvertError**

I've strictly followed the readme file instructions and executed
$> python3 ILAConfig.py config -vlog /home/alfredo/gatemate_ila/example_dut/blink/src/ -t blink

After some iterations I've found that within the ILAConfig.py script, the p_r tool is called which is responsible for the error.

I've reproduced the error with this command
$> p_r -i  /home/alfredo/gatemate_ila/net/ila_top_synth24-05-14_17-52-42.v               -o /home/alfredo/gatemate_ila/p_r_out/ila_top_24-05-14_17-52-42  -ccf /home/alfredo/gatemate_ila/src/ILA_top.ccf -v

Attached you can find the synthesized .v file and json to reconfig blink with ILA design.
[ila_config_blink_24-05-14_17-42-17.zip](https://github.com/colognechip/gatemate_ila/files/15319854/ila_config_blink_24-05-14_17-42-17.zip)

My system is a fresh new Linux ubuntu 24.04, just downloaded the last tools from MyGateMate and cloning the current gatemate_ila repository from github. 

Thank you for your support.

**Comment by D4VF0** [comment]
Thank you very much for your report. The problem has now been fixed.
