### ISSUE TITLE
Usability of this ila for GateMateA1-EVB

### ISSUE THREAD

**Issue by lollisoft** [colognechip/gatemate_ila#2]
Hello,

I would like to know, what must I do to get this design working with the Olimex GateMateA1-EVB board.

Is there any information for that board?

Thanks, Lothar

**Comment by D4VF0** [comment]
Hi Lothar,

the ILA can now be used with the Olimex GateMateA1-EVB. You need to modify the config.py file and install the pyusb library. I have also added the library to the requirements: https://github.com/colognechip/gatemate_ila#installation-of-external-python-packages
Follow the configuration steps to make the ILA ready for the Olimex GateMateA1-EVB: https://github.com/colognechip/gatemate_ila#use-with-the-olimex-gatematea1-evb
Issue closed with commit https://github.com/colognechip/gatemate_ila/commit/c0ec582.

Best regards, 
Dave
