### ISSUE TITLE
Improve operational system independence

### ISSUE THREAD

**Issue by Elektronikus** [colognechip/gatemate_ila#3]
In ILAConfig.py split("\\")[-1]] is used to separate the file names from the full path.
If split(os.path.sep)[-1]] is used, this will work for windows and for linux systems.

**Comment by D4VF0** [comment]
Thank you for identifying this issue. 
I have made the change in the commit:
https://github.com/colognechip/gatemate_ila/commit/c414ddd2963315187fd1c6dc30e313ec50b5d3d2
